### ISSUE TITLE
"Access denied" when creating new project

### ISSUE THREAD

**Issue by coenbijlsma** [daimor/NBStudio#5]
When creating a new project in NBStudio, after the wizard completes, Netbeans creates the project on disk, but gets access denied-errors when trying to connect to cache (2014.1). So I can walk through the wizard, it shows my namespaces and projects, but after the wizard, nothing. I use version 0.0.4-1027 of NBStudio.
The output from Netbeans is:

    Connect to jdbc:Cache://localhost:1972/MGH - Error: Failed to connect to URL: jdbc:Cache://localhost:1972/MGH caused by: java.sql.SQLException: [Cache JDBC] Communication link failure: Access DeniedUnderlying exception: java.sql.SQLException: [Cache JDBC] Communication link failure: Access Denied
    
    Connect to jdbc:Cache://localhost:1972/MGH - Error: Failed to connect to URL: jdbc:Cache://localhost:1972/MGH caused by: java.sql.SQLException: [Cache JDBC] Communication link failure: Access DeniedUnderlying exception: java.sql.SQLException: [Cache JDBC] Communication link failure: Access Denied`

Also, the mouse cursor shows the "busy" icon instead of the regular pointer thing.

**Comment by daimor** [comment]
OS name and version ?

**Comment by coenbijlsma** [comment]
OS: Windows 7, x64

**Comment by daimor** [comment]
Well, I tested it on Windows 7 x64 with installed by default Ensemble 2014.1
Cache for Windows (x86-64) 2014.1.1 (Build 702U) Wed May 14 2014 10:17:40 EDT
With minimal security, where _SYSTEM/SYS works. 
So, in that my system, it works well.

Can you say about your security settings, account _SYSTEM works with SYS password ?
Maybe something wrong with it, and I loose auth information somewhere.

**Comment by coenbijlsma** [comment]
I have it setup with default ( = different from minimal) security, and _SYSTEM/SYS doesn't work here; I have to use my own username/password.

**Comment by daimor** [comment]
Well, i think problem is here, I'll check it soon.

**Comment by coenbijlsma** [comment]
Just for your information: I enabled the _SYSTEM account, and then I don't get the error anymore.

**Comment by daimor** [comment]
OK, it is good.
